---

all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 146.190.118.102
          ansible_user: "{{ ansible_ssh_user }}"
          ansible_ssh_private_key_file: "{{ private_key_file }}"
