---

- hosts: all
  gather_facts: no
  tasks:

    - community.docker.docker_network:
        name: devops-example

    - community.docker.docker_container:
        name: app  # имя используется как домен
        # Обязатлеьно указываем тег, который хотим деплоить
        # Если образа на сервере нет, Ansible его автоматически скачает
        image: "kochetov/devops-example-app:{{ version }}"
        # Подключаем супервизор
        # Если контейнер остановится, например, из-за ошибок
        # супервизор докера его перезапустить
        restart_policy: always
        # Запускаем если не запущен
        state: started
        networks: # Добавляем контейнер в сеть
          - name: devops-example
        ports: # Больше не нужно выставлять наружу, потому что доступ идет через Caddy
        env: # Настраиваем
          NODE_ENV: production

    - community.docker.docker_container:
        name: caddy # имя используется как домен
        image: "kochetov/devops-example-caddy:{{ version }}"
        restart_policy: always
        state: started
        networks: # Добавляем контейнер в сеть
          - name: devops-example
        ports:
          - 80:80
          - 443:443
