---
- hosts: all
  gather_facts: no
  tasks:
    - name: Update package cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 604800 # 1 week

    - name: Install python3-pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      become: yes
      pip:
        name: docker
